### ISSUE TITLE
Support React Native

### ISSUE THREAD

**Issue by adamfisher** [timReynolds/react-visible#4]
It looks like this library could support react native if you just remove the div wrapper from the render method.

**Comment by timReynolds** [comment]
@adamfisher Sorry for not seeing this issue much much sooner. 

I've not used react-native but you're probably right as the divs aren't needed I'm going to remove them in the next version. 

Thanks for pointing this out.

**Comment by timReynolds** [comment]
@adamfisher This should be resolved in version 3.0.1 if you'd like to confirm I'll add some information about react-native support in the readme.
